# Generated by Django 4.2.6 on 2023-10-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook_profile',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_profile',
            field=models.CharField(blank=True, null=True),
        ),
    ]
