# Generated by Django 4.2.6 on 2023-10-20 16:44

import datetime
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('details', models.TextField(blank=True, max_length=200, null=True)),
                ('image1', models.ImageField(blank=True, null=True,)),
                ('image2', models.ImageField(blank=True, null=True, )),
                ('image3', models.ImageField(blank=True, null=True, )),
                ('image4', models.ImageField(blank=True, null=True,)),
                ('main_image', models.ImageField(blank=True, null=True, )),
                ('total_target', models.FloatField()),
                ('current_fund', models.FloatField()),
                ('tag1', models.CharField(blank=True, choices=[('hot', 'Hot'), ('new', 'New'), ('top', 'Top'), ('best', 'Best'), ('endingsoon', 'Ending Soon')], max_length=50, null=True)),
                ('tag2', models.CharField(blank=True, choices=[('hot', 'Hot'), ('new', 'New'), ('top', 'Top'), ('best', 'Best'), ('endingsoon', 'Ending Soon')], max_length=50, null=True)),
                ('tag3', models.CharField(blank=True, choices=[('hot', 'Hot'), ('new', 'New'), ('top', 'Top'), ('best', 'Best'), ('endingsoon', 'Ending Soon')], max_length=50, null=True)),
                ('tag4', models.CharField(blank=True, choices=[('hot', 'Hot'), ('new', 'New'), ('top', 'Top'), ('best', 'Best'), ('endingsoon', 'Ending Soon')], max_length=50, null=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2023, 10, 20, 16, 44, 48, 370963, tzinfo=datetime.timezone.utc))),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
