# Generated by Django 4.2.6 on 2023-10-20 17:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 17, 42, 9, 437688, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag1',
            field=models.CharField(blank=True, choices=[('Hot', 'Hot'), ('New', 'New'), ('Top', 'Top'), ('Best', 'Best'), ('EndingSoon', 'Ending Soon')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag2',
            field=models.CharField(blank=True, choices=[('Hot', 'Hot'), ('New', 'New'), ('Top', 'Top'), ('Best', 'Best'), ('EndingSoon', 'Ending Soon')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag3',
            field=models.CharField(blank=True, choices=[('Hot', 'Hot'), ('New', 'New'), ('Top', 'Top'), ('Best', 'Best'), ('EndingSoon', 'Ending Soon')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag4',
            field=models.CharField(blank=True, choices=[('Hot', 'Hot'), ('New', 'New'), ('Top', 'Top'), ('Best', 'Best'), ('EndingSoon', 'Ending Soon')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='projects.category'),
        ),
    ]
