# Generated by Django 4.2.6 on 2023-10-20 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_average_rate_project_num_of_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 18, 18, 16, 242911, tzinfo=datetime.timezone.utc)),
        ),
    ]
