# Generated by Django 4.2.6 on 2023-10-20 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 18, 18, 48, 487074, tzinfo=datetime.timezone.utc)),
        ),
    ]
