# Generated by Django 4.2.6 on 2023-10-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_current_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rate',
        ),
        migrations.AddField(
            model_name='rating',
            name='rate_value',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
