# Generated by Django 4.2.6 on 2023-10-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_is_featured_alter_comment_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
    ]
