# Generated by Django 4.2.6 on 2023-10-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_funding'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
